<?php
declare(strict_types=1);
namespace Syvo\BusinessDirectory;
if (!defined('ABSPATH')) { exit; }

final class Admin {
    public static function hooks(): void { add_action('admin_menu',[self::class,'menu']); add_action('admin_init',[self::class,'guardFrontendOnly']);add_action('admin_init',[self::class,'settings']);add_action('admin_post_syvo_bd_import_locations',[self::class,'importLocations']);add_action('admin_post_syvo_bd_reindex',[self::class,'reindex']); }
    public static function guardFrontendOnly(): void { if(is_admin() && !wp_doing_ajax() && is_user_logged_in() && !current_user_can('manage_options') && !current_user_can('edit_others_syvo_businesses')){ wp_safe_redirect(CorePages::url('dashboard')); exit; } }
    public static function menu(): void {
        add_menu_page('Syvo Business Directory','Syvo Directory','manage_options','syvo-bd',[self::class,'dashboard'],'dashicons-location-alt',26);
        add_submenu_page('syvo-bd','کسب‌وکارها','کسب‌وکارها','edit_others_syvo_businesses','edit.php?post_type='.SYVO_BD_CPT);
        add_submenu_page('syvo-bd','دسته‌بندی‌ها','دسته‌بندی‌ها','manage_options','edit-tags.php?taxonomy='.SYVO_BD_CATEGORY_TAX.'&post_type='.SYVO_BD_CPT);
        add_submenu_page('syvo-bd','خدمات','خدمات','manage_options','edit-tags.php?taxonomy='.SYVO_BD_SERVICE_TAX.'&post_type='.SYVO_BD_CPT);
        add_submenu_page('syvo-bd','Generated Pages','Generated Pages','manage_options','syvo-bd-pages',[self::class,'pages']);
        add_submenu_page('syvo-bd','AI','AI','manage_options','syvo-bd-ai',[self::class,'ai']);
        add_submenu_page('syvo-bd','Settings','Settings','manage_options','syvo-bd-settings',[self::class,'settingsPage']);
        add_submenu_page('syvo-bd','Logs','Logs','manage_options','syvo-bd-logs',[self::class,'logs']);
        add_submenu_page('syvo-bd','Diagnostics','Diagnostics','manage_options','syvo-bd-diagnostics',[self::class,'diagnostics']);
    }
    public static function settings(): void { register_setting('syvo_bd_settings','syvo_bd_map_config',['sanitize_callback'=>[self::class,'sanitizeMap']]);register_setting('syvo_bd_settings','syvo_bd_delete_data_on_uninstall',['sanitize_callback'=>'rest_sanitize_boolean']); }
    public static function sanitizeMap($value): array { $v=(array)$value;return ['tile_url'=>esc_url_raw((string)($v['tile_url']??'https://tile.openstreetmap.org/{z}/{x}/{y}.png')),'tile_attribution'=>sanitize_text_field((string)($v['tile_attribution']??'© OpenStreetMap contributors')),'geocoder_url'=>esc_url_raw((string)($v['geocoder_url']??'https://nominatim.openstreetmap.org/reverse')),'geocoder_user_agent'=>sanitize_text_field((string)($v['geocoder_user_agent']??'Syvo Business Directory')),'geocoder_api_key'=>sanitize_text_field((string)($v['geocoder_api_key']??''))]; }
    public static function dashboard(): void { self::wrap('Dashboard',function(){echo'<div class="wrap"><h1>Syvo Business Directory</h1><p>هسته دایرکتوری کسب‌وکار سایوو.</p><pre style="background:#101828;color:#fff;padding:20px;border-radius:12px;overflow:auto;max-width:1000px">'.esc_html(wp_json_encode(Diagnostics::all(),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)).'</pre><form method="post" action="'.esc_url(admin_url('admin-post.php')).'">'.wp_nonce_field('syvo_bd_import','_wpnonce',true,false).'<input type="hidden" name="action" value="syvo_bd_import_locations"><button class="button button-primary">Import / Refresh Locations</button></form></div>';}); }
    public static function pages(): void { self::wrap('Generated Pages',function(){global $wpdb;$rows=$wpdb->get_results('SELECT * FROM '.DB::table('directory_pages').' ORDER BY updated_at DESC LIMIT 200',ARRAY_A)?:[];echo'<div class="wrap"><h1>Generated Directory Pages</h1><table class="widefat striped"><thead><tr><th>URL</th><th>Type</th><th>Status</th><th>Business Count</th><th>Dirty</th></tr></thead><tbody>';foreach($rows as $r)echo'<tr><td><a target="_blank" href="'.esc_url(home_url($r['url'])).'">'.esc_html($r['url']).'</a></td><td>'.esc_html($r['location_type']).'</td><td>'.esc_html($r['status']).'</td><td>'.esc_html($r['business_count']).'</td><td>'.esc_html($r['dirty']).'</td></tr>';echo'</tbody></table></div>';}); }
    public static function ai(): void { self::wrap('AI',function(){global $wpdb; $queue=(int)$wpdb->get_var("SELECT COUNT(*) FROM ".DB::table('jobs')." WHERE status IN ('pending','running')"); $last=$wpdb->get_row("SELECT * FROM ".DB::table('ai_logs')." ORDER BY id DESC LIMIT 1",ARRAY_A); echo'<div class="wrap"><h1>AI</h1><p>Provider: WordPress AI Client</p><p>Status: <strong>'.(AIService::status()['configured']?'Configured':'Not Configured').'</strong></p><p>Queue: '.esc_html((string)$queue).'</p><p>Last request: '.esc_html((string)($last['created_at']??'—')).' '.esc_html((string)($last['status']??'—')).'</p><p>API key is not stored or exposed by this plugin.</p></div>';}); }
    public static function settingsPage(): void { self::wrap('Settings',function(){ $c=(array)get_option('syvo_bd_map_config',[]);echo'<div class="wrap"><h1>Settings</h1><form method="post" action="options.php">';settings_fields('syvo_bd_settings');echo'<table class="form-table"><tr><th>Tile URL</th><td><input class="regular-text" name="syvo_bd_map_config[tile_url]" value="'.esc_attr($c['tile_url']??'').'" /></td></tr><tr><th>Tile Attribution</th><td><input class="regular-text" name="syvo_bd_map_config[tile_attribution]" value="'.esc_attr($c['tile_attribution']??'').'" /></td></tr><tr><th>Reverse Geocoder URL</th><td><input class="regular-text" name="syvo_bd_map_config[geocoder_url]" value="'.esc_attr($c['geocoder_url']??'').'" /></td></tr><tr><th>User-Agent</th><td><input class="regular-text" name="syvo_bd_map_config[geocoder_user_agent]" value="'.esc_attr($c['geocoder_user_agent']??'').'" /></td></tr><tr><th>Provider Key</th><td><input type="password" class="regular-text" name="syvo_bd_map_config[geocoder_api_key]" value="'.esc_attr($c['geocoder_api_key']??'').'" autocomplete="new-password" /></td></tr></table>';submit_button();echo'</form><hr><h2>Uninstall</h2><p>By default real business data is retained on uninstall.</p><label><input form="" type="checkbox" disabled> Complete deletion must be intentionally configured in code/option.</label></div>';}); }
    public static function logs(): void { self::wrap('Logs',function(){global $wpdb;$rows=$wpdb->get_results('SELECT * FROM '.DB::table('ai_logs').' ORDER BY id DESC LIMIT 200',ARRAY_A)?:[];echo'<div class="wrap"><h1>AI Logs</h1><table class="widefat striped"><thead><tr><th>Time</th><th>Job</th><th>Entity</th><th>Status</th><th>Message</th></tr></thead><tbody>';foreach($rows as $r)echo'<tr><td>'.esc_html($r['created_at']).'</td><td>'.esc_html($r['job_type']).'</td><td>'.esc_html($r['entity_id']).'</td><td>'.esc_html($r['status']).'</td><td>'.esc_html($r['safe_message']).'</td></tr>';echo'</tbody></table></div>';}); }
    public static function diagnostics(): void { self::wrap('Diagnostics',function(){echo'<div class="wrap"><h1>Diagnostics</h1><pre style="background:#101828;color:#fff;padding:20px;overflow:auto">'.esc_html(wp_json_encode(Diagnostics::all(),JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)).'</pre></div>';}); }
    public static function importLocations(): void { if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('syvo_bd_import');$job=Queue::enqueue('import_locations','system',0,[],'locations:'.SYVO_BD_LOCATION_DATASET_VERSION,1);wp_safe_redirect(add_query_arg(['page'=>'syvo-bd','updated'=>1],admin_url('admin.php')));exit; }
    public static function reindex(): void { if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('syvo_bd_reindex');foreach(get_posts(['post_type'=>SYVO_BD_CPT,'post_status'=>['publish','draft','private'],'posts_per_page'=>200,'fields'=>'ids']) as $id)Queue::enqueue('refresh_business_index',SYVO_BD_CPT,(int)$id,['business_id'=>(int)$id],'business:index:'.$id,10);wp_safe_redirect(admin_url('admin.php?page=syvo-bd'));exit; }
    private static function wrap(string $title,callable $cb): void { echo'<div class="syvo-bd-admin">';$cb();echo'</div>'; }
}
