<?php
declare(strict_types=1);
namespace Syvo\BusinessDirectory;
if (!defined('ABSPATH')) { exit; }

final class Frontend {
    public static function hooks(): void {
        add_shortcode('syvo_business_register',[self::class,'registerShortcode']);
        add_shortcode('syvo_business_login',[self::class,'loginShortcode']);
        add_shortcode('syvo_business_dashboard',[self::class,'dashboardShortcode']);
        add_shortcode('syvo_business_search',[self::class,'searchShortcode']);
        add_shortcode('syvo_directory',[self::class,'directoryShortcode']);
        add_shortcode('syvo_business_profile',[self::class,'profileShortcode']);
        add_shortcode('syvo_directory_landing',[self::class,'landingShortcode']);
        add_filter('the_content', [self::class,'ensureAssetsInShortcode'],1);
    }
    public static function ensureAssetsInShortcode(string $content): string { if(str_contains($content,'[syvo_') || RewriteService::current_route()) FrontendAssets::enqueue(); return $content; }
    public static function registerShortcode(): string { FrontendAssets::enqueue(); if(is_user_logged_in())return self::renderRegisterWizard();return '<section class="syvo-bd-shell syvo-bd-register" data-syvo-bd-register><div class="syvo-bd-card"><div class="syvo-bd-kicker">SYVO BUSINESS DIRECTORY</div><h1>ثبت کسب‌وکار</h1><p class="syvo-bd-muted">حساب شما مالک کسب‌وکار خواهد بود و اطلاعات حساس عمومی نمی‌شود.</p>'.self::renderAccountStep().'</div></section>'; }
    public static function loginShortcode(): string { FrontendAssets::enqueue();if(is_user_logged_in())return '<div class="syvo-bd-shell"><div class="syvo-bd-card"><h2>شما وارد شده‌اید</h2><a class="syvo-bd-btn" href="'.esc_url(CorePages::url('dashboard')).'">ورود به پنل</a></div></div>';ob_start();echo'<section class="syvo-bd-shell"><div class="syvo-bd-card"><div class="syvo-bd-kicker">ACCOUNT</div><h1>ورود</h1>';wp_login_form(['echo'=>true,'redirect'=>CorePages::url('dashboard'),'remember'=>true]);echo'<p class="syvo-bd-muted">حساب ندارید؟ <a href="'.esc_url(CorePages::url('register-business')).'">ثبت کسب‌وکار</a></p></div></section>';return ob_get_clean(); }
    public static function dashboardShortcode(): string { FrontendAssets::enqueue();if(!is_user_logged_in())return self::loginShortcode();$posts=get_posts(['post_type'=>SYVO_BD_CPT,'post_status'=>['publish','draft','private','trash'],'author'=>get_current_user_id(),'posts_per_page'=>50,'orderby'=>'date','order'=>'DESC']);ob_start();echo'<section class="syvo-bd-shell"><div class="syvo-bd-card"><div class="syvo-bd-dashboard-head"><div><div class="syvo-bd-kicker">MY BUSINESSES</div><h1>پنل کسب‌وکار</h1></div><a class="syvo-bd-btn" href="'.esc_url(CorePages::url('register-business')).'">افزودن کسب‌وکار</a></div><div class="syvo-bd-grid">';foreach($posts as $p){echo'<article class="syvo-bd-business-card"><div><span class="syvo-bd-status">'.esc_html($p->post_status).'</span><h3>'.esc_html($p->post_title).'</h3><p>'.esc_html(mb_substr(wp_strip_all_tags($p->post_content),0,150)).'</p></div><div class="syvo-bd-card-actions">';if($p->post_status==='publish')echo'<a href="'.esc_url(get_permalink($p->ID)).'" class="syvo-bd-link">مشاهده</a>';echo'<a href="'.esc_url(home_url('/dashboard/?business_id='.$p->ID)).'" class="syvo-bd-link" data-edit-business="'.esc_attr($p->ID).'">ویرایش</a></div></article>';}if(!$posts)echo'<div class="syvo-bd-empty">هنوز کسب‌وکاری ثبت نکرده‌اید.</div>';echo'</div></div></section>';return ob_get_clean(); }
    public static function searchShortcode(): string { FrontendAssets::enqueue();return '<section class="syvo-bd-shell" data-syvo-bd-search><div class="syvo-bd-card"><div class="syvo-bd-kicker">DISCOVER LOCAL BUSINESS</div><h1>جستجوی کسب‌وکارها</h1><div class="syvo-bd-searchbar"><input type="search" data-search-q placeholder="مثلاً طراحی سایت در کرمان"><button class="syvo-bd-btn" data-search-submit>جستجو</button></div><div class="syvo-bd-filter-grid"><select data-search-province><option value="">استان</option></select><select data-search-county disabled><option value="">شهرستان</option></select><select data-search-city disabled><option value="">شهر</option></select><button class="syvo-bd-btn secondary" data-use-location>استفاده از موقعیت من</button></div><div class="syvo-bd-results" data-search-results></div></div></section>'; }
    public static function directoryShortcode(): string { FrontendAssets::enqueue();return self::renderDirectoryHome(); }
    public static function profileShortcode(): string { FrontendAssets::enqueue();$id=absint($_GET['business_id']??get_queried_object_id());return $id?self::render_business_profile($id):'<div class="syvo-bd-empty">کسب‌وکار یافت نشد.</div>'; }
    public static function landingShortcode(): string { FrontendAssets::enqueue();$route=RewriteService::current_route();if(!$route)return'<div class="syvo-bd-empty">صفحه دایرکتوری یافت نشد.</div>';$ctx=PageService::context($route['route'],$route['category'],$route['location'],$route['parent_category']);return $ctx?self::renderLanding($ctx):self::notFound(); }
    public static function render_virtual_request(): string { FrontendAssets::enqueue();$route=RewriteService::current_route();if(!$route)return '<div class="syvo-bd-shell"><div class="syvo-bd-empty">صفحه پیدا نشد.</div></div>';if($route['route']==='directory')return self::renderDirectoryHome();$ctx=PageService::context($route['route'],$route['category'],$route['location'],$route['parent_category']);return $ctx?self::renderLanding($ctx):self::notFound(); }
    private static function notFound(): string { status_header(404);return'<section class="syvo-bd-shell"><div class="syvo-bd-card"><h1>صفحه دایرکتوری پیدا نشد</h1><p class="syvo-bd-muted">این ترکیب دسته و مکان هنوز کسب‌وکار منتشرشده‌ای ندارد.</p><a class="syvo-bd-btn" href="'.esc_url(CorePages::url('hiper')).'">بازگشت به دایرکتوری</a></div></section>'; }
    private static function renderDirectoryHome(): string { $cats=CategoryService::allTree();ob_start();echo'<section class="syvo-bd-shell syvo-bd-directory-home"><div class="syvo-bd-hero"><div class="syvo-bd-kicker">SYVO / HIPER</div><h1>کسب‌وکارهای محلی را پیدا کنید</h1><p>جستجو بر اساس خدمت، دسته، شهر و موقعیت مکانی؛ فقط اطلاعات واقعی کسب‌وکارهای منتشرشده نمایش داده می‌شود.</p><a class="syvo-bd-btn" href="'.esc_url(CorePages::url('register-business')).'">ثبت کسب‌وکار</a></div><div class="syvo-bd-card"><h2>دسته‌بندی‌ها</h2><div class="syvo-bd-category-grid">';self::printCategoryTree($cats);echo'</div></div></section>';return ob_get_clean(); }
    private static function printCategoryTree(array $nodes): void { foreach($nodes as $node){echo'<div class="syvo-bd-category-item"><a href="'.esc_url(add_query_arg('category',sanitize_title($node['slug']),CorePages::url('directory-search'))).'">'.esc_html($node['name']).'</a>';if(!empty($node['children'])){echo'<div class="syvo-bd-category-children">';self::printCategoryTree($node['children']);echo'</div>'; }echo'</div>'; } }
    private static function renderLanding(array $ctx): string { $items=SearchService::search(['category_id'=>(int)$ctx['category']->term_id,'city_id'=>$ctx['type']==='city'?(int)$ctx['location']['id']:0,'county_id'=>$ctx['type']==='county'?(int)$ctx['location']['id']:0,'province_id'=>$ctx['type']==='province'?(int)$ctx['location']['id']:0,'per_page'=>50]);$pageId=PageService::findPageId((int)$ctx['category']->term_id,$ctx['type'],(int)$ctx['location']['id']);$page=$pageId?PageService::get($pageId):null;ob_start();echo'<main class="syvo-bd-shell syvo-bd-landing" data-landing-category="'.esc_attr($ctx['category']->term_id).'" data-landing-location="'.esc_attr($ctx['location']['id']).'"><div class="syvo-bd-landing-head"><div><div class="syvo-bd-kicker">SYVO / HIPER</div><div class="syvo-bd-breadcrumb"><a href="'.esc_url(home_url('/')).'">خانه</a><span>›</span><a href="'.esc_url(CorePages::url('hiper')).'">دایرکتوری</a><span>›</span><span>'.esc_html($ctx['category']->name).'</span><span>›</span><span>'.esc_html($ctx['location']['name_fa']).'</span></div><h1>'.esc_html($ctx['category']->name).' در '.esc_html($ctx['location']['name_fa']).'</h1><p class="syvo-bd-muted">'.esc_html((string)($ctx['business_count'])).' کسب‌وکار منتشرشده در این دسته و مکان.</p></div></div><div class="syvo-bd-landing-grid"><section><div class="syvo-bd-grid" data-business-results>';foreach($items as $item)self::businessCard($item);if(!$items)echo'<div class="syvo-bd-empty">در حال حاضر کسب‌وکار منتشرشده‌ای در این ترکیب وجود ندارد.</div>';echo'</div>';if($page&&!empty($page['seo_content']))echo'<section class="syvo-bd-seo-content">'.wp_kses_post($page['seo_content']).'</section></section><aside class="syvo-bd-map-panel"><div class="syvo-bd-map" data-map data-lat="'.esc_attr($items[0]['lat']??$ctx['location']['latitude']??35.6892).'" data-lng="'.esc_attr($items[0]['lng']??$ctx['location']['longitude']??51.389).'"> <div class="syvo-bd-map-attribution">© OpenStreetMap contributors</div></div></aside></div></main>';return ob_get_clean(); }
    private static function businessCard(array $item): void { echo'<article class="syvo-bd-business-card"><div class="syvo-bd-card-main"><div class="syvo-bd-status">'.($item['verified']?'تأییدشده':'پروفایل معمولی').'</div><h3><a href="'.esc_url(get_permalink($item['id'])).'">'.esc_html($item['name']).'</a></h3><p>'.esc_html(mb_substr(wp_strip_all_tags((string)$item['description']),0,180)).'</p><div class="syvo-bd-tags">';foreach(array_slice((array)$item['services'],0,4) as $service)echo'<span>'.esc_html($service).'</span>';echo'</div></div><div class="syvo-bd-card-meta"><span>'.esc_html((string)($item['city']['name_fa']??'')).'</span><span>'.esc_html((string)$item['completeness']).'% تکمیل</span></div></article>'; }
    public static function render_business_profile(int $id): string { if(!BusinessService::canViewPublic($id))return self::notFound();$p=BusinessService::publicData($id);ob_start();echo'<section class="syvo-bd-shell syvo-bd-profile"><div class="syvo-bd-profile-grid"><div class="syvo-bd-card"><div class="syvo-bd-kicker">BUSINESS PROFILE</div><h1>'.esc_html($p['name']).'</h1>';if($p['logo_id']){ $logoUrl=wp_get_attachment_image_url((int)$p['logo_id'],'medium'); if($logoUrl)echo'<img class="syvo-bd-profile-logo" src="'.esc_url($logoUrl).'" alt="'.esc_attr($p['name']).'">'; } if($p['brand'])echo'<div class="syvo-bd-brand">'.esc_html($p['brand']).'</div>';echo'<p class="syvo-bd-profile-desc">'.wp_kses_post(wpautop($p['description'])).'</p><div class="syvo-bd-tags">';foreach($p['categories'] as $cat)echo'<span>'.esc_html($cat['name']).'</span>';foreach($p['services'] as $service)echo'<span>'.esc_html($service).'</span>';echo'</div><div class="syvo-bd-contact-grid">';if($p['mobile'])echo'<a href="tel:'.esc_attr($p['mobile']).'">'.esc_html($p['mobile']).'</a>';if($p['website'])echo'<a href="'.esc_url($p['website']).'" rel="nofollow">وب‌سایت</a>';if($p['instagram'])echo'<a href="'.esc_url($p['instagram']).'" rel="nofollow">اینستاگرام</a>';if($p['email'])echo'<a href="mailto:'.esc_attr($p['email']).'">ایمیل</a>';echo'</div><dl class="syvo-bd-address-list"><div><dt>استان</dt><dd>'.esc_html($p['province']['name_fa']??'').'</dd></div><div><dt>شهرستان</dt><dd>'.esc_html($p['county']['name_fa']??'').'</dd></div><div><dt>شهر</dt><dd>'.esc_html($p['city']['name_fa']??'').'</dd></div><div><dt>آدرس</dt><dd>'.esc_html($p['address']).'</dd></div></dl><div class="syvo-bd-gallery">';foreach($p['gallery_ids'] as $gid){$gurl=wp_get_attachment_image_url((int)$gid,'medium');$galt=(string)get_post_meta((int)$gid,'_wp_attachment_image_alt',true);if($gurl)echo'<img src="'.esc_url($gurl).'" alt="'.esc_attr($galt?:$p['name']).'">';}echo'</div></div><aside class="syvo-bd-map-panel"><div class="syvo-bd-map" data-map data-lat="'.esc_attr($p['lat']).'" data-lng="'.esc_attr($p['lng']).'"></div></aside></div></section>';return ob_get_clean(); }
    private static function renderRegisterWizard(): string { ob_start();echo'<section class="syvo-bd-shell syvo-bd-register" data-syvo-bd-wizard><div class="syvo-bd-card"><div class="syvo-bd-kicker">SYVO / BUSINESS</div><h1>ثبت کسب‌وکار</h1><p class="syvo-bd-muted">اطلاعات کسب‌وکارتان را مرحله‌به‌مرحله کامل کنید.</p><div class="syvo-bd-stepper" data-stepper></div><div class="syvo-bd-step-label" data-step-label></div><form data-business-form novalidate>';echo self::renderWizardStep(1,'حساب کاربری',self::renderAccountFields());echo self::renderWizardStep(2,'اطلاعات کسب‌وکار',self::renderBusinessFields());echo self::renderWizardStep(3,'دسته و خدمات',self::renderCategoryFields());echo self::renderWizardStep(4,'موقعیت مکانی',self::renderLocationFields());echo self::renderWizardStep(5,'آدرس',self::renderAddressFields());echo self::renderWizardStep(6,'تصاویر',self::renderMediaFields());echo self::renderWizardStep(7,'توضیحات',self::renderDescriptionFields());echo self::renderWizardStep(8,'بازبینی', '<div data-review></div>');echo self::renderWizardStep(9,'ثبت نهایی','<div class="syvo-bd-success" data-success></div>');echo'<div class="syvo-bd-wizard-actions"><div class="syvo-bd-step-message" data-step-message></div><button type="button" class="syvo-bd-btn secondary" data-prev>قبلی</button><button type="button" class="syvo-bd-btn" data-next>ادامه</button><button type="submit" class="syvo-bd-btn" data-submit hidden>ثبت نهایی</button><button type="button" class="syvo-bd-btn ghost" data-draft>ذخیره پیش‌نویس</button></div></form></div></section>';return ob_get_clean(); }
    private static function renderAccountStep(): string { return '<form data-register-account><div class="syvo-bd-form-grid">'.self::input('name','نام').self::input('last_name','نام خانوادگی').self::input('mobile','شماره موبایل','tel').self::input('email','ایمیل','email').self::input('national_id','کد ملی').self::input('password','رمز عبور','password').self::input('password_confirm','تکرار رمز عبور','password').'<div class="syvo-bd-honeypot">'.self::input('website_url','وب‌سایت','url').'</div></div><button class="syvo-bd-btn" type="submit">ساخت حساب و ادامه</button><div data-account-message></div></form>'; }
    private static function renderWizardStep(int $n,string $title,string $body): string { return'<section class="syvo-bd-step" data-step="'.esc_attr($n).'"><div class="syvo-bd-step-title"><span>'.esc_html($n).'</span><div><strong>'.esc_html($title).'</strong></div></div>'.$body.'</section>'; }
    private static function renderAccountFields(): string { return '<p class="syvo-bd-muted">حساب فعلی شما برای مالکیت این کسب‌وکار استفاده می‌شود.</p>'; }
    private static function renderBusinessFields(): string { return '<div class="syvo-bd-form-grid">'.self::input('name','نام کسب‌وکار').self::input('brand','نام کوتاه / برند').self::input('business_mobile','موبایل کسب‌وکار','tel').self::input('phone','تلفن ثابت','tel').self::input('business_email','ایمیل کسب‌وکار','email').self::input('website','وب‌سایت','url').self::input('instagram','اینستاگرام','url').self::input('whatsapp','واتساپ').'</div>'; }
    private static function renderCategoryFields(): string { return '<div class="syvo-bd-category-box" data-category-tree></div><label class="syvo-bd-field full"><span>خدمات</span><textarea name="services_text" rows="4" placeholder="هر خدمت را با ویرگول جدا کنید"></textarea></label>'; }
    private static function renderLocationFields(): string { return '<div class="syvo-bd-form-grid"><label class="syvo-bd-field"><span>استان</span><select name="province_id" data-province required><option value="">انتخاب کنید</option></select></label><label class="syvo-bd-field"><span>شهرستان</span><select name="county_id" data-county required disabled><option value="">ابتدا استان</option></select></label><label class="syvo-bd-field"><span>شهر</span><select name="city_id" data-city required disabled><option value="">ابتدا شهرستان</option></select></label></div><div class="syvo-bd-map-controls"><button type="button" class="syvo-bd-btn secondary" data-current-location>استفاده از موقعیت فعلی</button><button type="button" class="syvo-bd-btn secondary" data-reverse>تکمیل آدرس از روی نقشه</button></div><div class="syvo-bd-map" data-form-map data-lat="" data-lng=""></div><input type="hidden" name="lat"><input type="hidden" name="lng">'; }
    private static function renderAddressFields(): string { return '<div class="syvo-bd-form-grid">'.self::input('neighborhood','محله').self::input('street','خیابان').self::input('alley','کوچه').self::input('plaque','پلاک').self::input('unit','واحد').self::input('floor','طبقه').self::input('postal_code','کدپستی').'<label class="syvo-bd-field full"><span>آدرس کامل</span><textarea name="address" rows="4"></textarea></label></div>'; }
    private static function renderMediaFields(): string { return '<div class="syvo-bd-upload-grid"><label class="syvo-bd-upload"><span>لوگو</span><input type="file" accept="image/jpeg,image/png,image/webp" data-upload-logo></label><label class="syvo-bd-upload"><span>تصویر اصلی</span><input type="file" accept="image/jpeg,image/png,image/webp" data-upload-featured></label><label class="syvo-bd-upload"><span>گالری</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple data-upload-gallery></label></div><div class="syvo-bd-preview" data-media-preview></div>'; }
    private static function renderDescriptionFields(): string { return '<label class="syvo-bd-field full"><span>توضیحات کسب‌وکار</span><textarea name="description" rows="10" placeholder="اطلاعات واقعی کسب‌وکار، خدمات و شیوه ارتباط..."></textarea></label>'; }
    private static function input(string $name,string $label,string $type='text'): string { return'<label class="syvo-bd-field"><span>'.esc_html($label).'</span><input type="'.$type.'" name="'.esc_attr($name).'" autocomplete="off"></label>'; }
    public static function renderVirtualSearchResult(array $items): string { ob_start();foreach($items as $item)self::businessCard($item);return ob_get_clean(); }
    public static function render_search_card_data(array $items): array { return array_map(static fn($i)=>['id'=>$i['id'],'name'=>$i['name'],'url'=>get_permalink($i['id']),'description'=>wp_strip_all_tags((string)$i['description']),'city'=>$i['city']['name_fa']??'','services'=>$i['services'],'completeness'=>$i['completeness']],$items); }
}
