<?php
declare(strict_types=1);
namespace Syvo\BusinessDirectory;
if (!defined('ABSPATH')) { exit; }

final class Rest {
    public static function hooks(): void { add_action('rest_api_init',[self::class,'register']); }
    public static function register(): void {
        $n=SYVO_BD_REST_NAMESPACE;
        register_rest_route($n,'/locations/provinces',['methods'=>'GET','callback'=>static fn()=>self::locations('province',0),'permission_callback'=>'__return_true']);
        register_rest_route($n,'/locations/counties',['methods'=>'GET','callback'=>static fn(\WP_REST_Request $r)=>self::locations('county',absint($r->get_param('province_id'))),'permission_callback'=>'__return_true','args'=>['province_id'=>['required'=>true,'type'=>'integer']]]);
        register_rest_route($n,'/locations/cities',['methods'=>'GET','callback'=>static fn(\WP_REST_Request $r)=>self::locations('city',absint($r->get_param('county_id'))),'permission_callback'=>'__return_true','args'=>['county_id'=>['required'=>true,'type'=>'integer']]]);
        register_rest_route($n,'/categories',['methods'=>'GET','callback'=>static fn()=>rest_ensure_response(CategoryService::allTree()),'permission_callback'=>'__return_true']);
        register_rest_route($n,'/reverse-geocode',['methods'=>'GET','callback'=>static fn(\WP_REST_Request $r)=>self::reverse($r),'permission_callback'=>'__return_true']);
        register_rest_route($n,'/search',['methods'=>'GET','callback'=>static function(\WP_REST_Request $r){$args=$r->get_params();if(!empty($args['category_slug'])&&!isset($args['category_id'])){$term=get_term_by('slug',sanitize_title((string)$args['category_slug']),SYVO_BD_CATEGORY_TAX);if($term&&!is_wp_error($term))$args['category_id']=(int)$term->term_id;}return rest_ensure_response(SearchService::search($args));},'permission_callback'=>'__return_true']);
        register_rest_route($n,'/register',['methods'=>'POST','callback'=>[self::class,'registerUser'],'permission_callback'=>'__return_true']);
        register_rest_route($n,'/draft',['methods'=>['GET','POST'],'callback'=>[self::class,'draft'],'permission_callback'=>[self::class,'private_permission']]);
        register_rest_route($n,'/businesses',['methods'=>'POST','callback'=>[self::class,'createBusiness'],'permission_callback'=>[self::class,'private_permission']]);
        register_rest_route($n,'/businesses/mine',['methods'=>'GET','callback'=>[self::class,'mine'],'permission_callback'=>[self::class,'private_permission']]);
        register_rest_route($n,'/businesses/(?P<id>\d+)',['methods'=>'GET','callback'=>[self::class,'getBusiness'],'permission_callback'=>'__return_true']);
        register_rest_route($n,'/businesses/(?P<id>\d+)',['methods'=>['PUT','PATCH'],'callback'=>[self::class,'updateBusiness'],'permission_callback'=>[self::class,'private_permission']]);
        register_rest_route($n,'/businesses/(?P<id>\d+)',['methods'=>'DELETE','callback'=>[self::class,'deleteBusiness'],'permission_callback'=>[self::class,'private_permission']]);
        register_rest_route($n,'/upload',['methods'=>'POST','callback'=>[self::class,'upload'],'permission_callback'=>[self::class,'private_permission']]);
        register_rest_route($n,'/diagnostics',['methods'=>'GET','callback'=>static fn()=>rest_ensure_response(Diagnostics::all()),'permission_callback'=>static fn()=>current_user_can('manage_options')]);
    }
    public static function private_permission(): bool { return is_user_logged_in(); }
    private static function locations(string $type,int $parent): \WP_REST_Response|\WP_Error { if($type!=='province'&&$parent<1)return new \WP_Error('invalid_parent','parent id required',['status'=>400]); global $wpdb;$table=DB::table('locations');$rows=$type==='province'?$wpdb->get_results($wpdb->prepare("SELECT id,name_fa,name_en,slug,latitude,longitude FROM {$table} WHERE location_type=%s ORDER BY name_fa",$type),ARRAY_A):LocationService::children($type,$parent);return rest_ensure_response($rows); }
    private static function reverse(\WP_REST_Request $r): \WP_REST_Response|\WP_Error { $lat=(float)$r->get_param('lat');$lng=(float)$r->get_param('lng');if(!Security::rate_limit('reverse_geocode',Request::ip(),30,60))return new \WP_Error('rate_limited','درخواست‌های موقعیت مکانی بیش از حد مجاز است.',['status'=>429]);$out=LocationService::reverseGeocode($lat,$lng);return is_wp_error($out)?$out:rest_ensure_response($out); }
    public static function registerUser(\WP_REST_Request $r): \WP_REST_Response|\WP_Error {
        if(!Security::rate_limit('register',Request::ip(),5,900))return new \WP_Error('rate_limited','درخواست‌های ثبت‌نام بیش از حد مجاز است.',['status'=>429]);$d=Request::json($r);if(!empty($d['website_url']))return new \WP_Error('spam','درخواست رد شد.',['status'=>400]);
        $name=sanitize_text_field((string)($d['name']??''));$last=sanitize_text_field((string)($d['last_name']??''));$email=Security::email((string)($d['email']??''));$mobile=Security::normalize_mobile((string)($d['mobile']??''));$nid=Security::normalize_digits((string)($d['national_id']??''));$pass=(string)($d['password']??'');$confirm=(string)($d['password_confirm']??'');
        if($name===''||$last===''||$email===''||is_wp_error($mobile)||!Security::validate_national_id($nid)||strlen($pass)<10||$pass!==$confirm)return new \WP_Error('invalid_registration','اطلاعات ثبت‌نام کامل یا معتبر نیست.',['status'=>400]);
        if(email_exists($email))return new \WP_Error('email_exists','این ایمیل قبلاً ثبت شده است.',['status'=>409]);
        $nidFp=Security::fingerprint($nid);
        $users=get_users(['fields'=>'ids','number'=>1,'meta_key'=>BusinessMeta::NATIONAL_ID_FP,'meta_value'=>$nidFp]);
        if(!empty($users))return new \WP_Error('national_id_exists','این کد ملی قبلاً ثبت شده است.',['status'=>409]);
        $login='syvo_'.strtolower(wp_generate_password(10,false,false)); while(username_exists($login))$login='syvo_'.strtolower(wp_generate_password(10,false,false));
        $uid=wp_create_user($login,$pass,$email);if(is_wp_error($uid))return $uid;$uid=(int)$uid;wp_update_user(['ID'=>$uid,'first_name'=>$name,'last_name'=>$last,'role'=>'syvo_business_owner']);update_user_meta($uid,BusinessMeta::MOBILE,$mobile);$enc=Security::encrypt_sensitive($nid);if(is_wp_error($enc)){wp_delete_user($uid);return $enc;}update_user_meta($uid,BusinessMeta::NATIONAL_ID,$enc);update_user_meta($uid,BusinessMeta::NATIONAL_ID_FP,$nidFp);wp_set_auth_cookie($uid,true);do_action('syvo_bd_user_registered',$uid);return rest_ensure_response(['success'=>true,'user_id'=>$uid,'dashboard_url'=>CorePages::url('dashboard')]);
    }
    public static function createBusiness(\WP_REST_Request $r): \WP_REST_Response|\WP_Error { if(!Request::nonce_ok($r))return new \WP_Error('invalid_nonce','نشست فرم معتبر نیست.',['status'=>403]); $d=Request::json($r);$uid=get_current_user_id();$id=BusinessService::create($uid,$d);if(is_wp_error($id))return $id;return rest_ensure_response(BusinessService::publicData($id)); }
    public static function mine(): \WP_REST_Response { $posts=get_posts(['post_type'=>SYVO_BD_CPT,'post_status'=>['publish','draft','private','trash'],'author'=>get_current_user_id(),'posts_per_page'=>50,'orderby'=>'date','order'=>'DESC']);return rest_ensure_response(array_map(static fn($p)=>['id'=>$p->ID,'name'=>$p->post_title,'status'=>$p->post_status,'edit_url'=>home_url('/dashboard/?business_id='.$p->ID)],$posts)); }
    public static function getBusiness(\WP_REST_Request $r): \WP_REST_Response|\WP_Error { $id=absint($r['id']);if(!BusinessService::canViewPublic($id))return new \WP_Error('not_found','کسب‌وکار یافت نشد.',['status'=>404]);return rest_ensure_response(BusinessService::publicData($id)); }
    public static function updateBusiness(\WP_REST_Request $r): \WP_REST_Response|\WP_Error { if(!Request::nonce_ok($r))return new \WP_Error('invalid_nonce','نشست فرم معتبر نیست.',['status'=>403]); $id=absint($r['id']);$d=Request::json($r);$res=BusinessService::update($id,get_current_user_id(),$d);if(is_wp_error($res))return$res;return rest_ensure_response(BusinessService::publicData($id)); }
    public static function deleteBusiness(\WP_REST_Request $r): \WP_REST_Response|\WP_Error { if(!Request::nonce_ok($r))return new \WP_Error('invalid_nonce','نشست فرم معتبر نیست.',['status'=>403]); $id=absint($r['id']);if(!BusinessService::canEdit($id,get_current_user_id()))return new \WP_Error('forbidden','دسترسی ندارید.',['status'=>403]);$post=wp_trash_post($id);if(!$post)return new \WP_Error('delete_failed','حذف کسب‌وکار انجام نشد.');return rest_ensure_response(['success'=>true]); }
    public static function upload(\WP_REST_Request $r): \WP_REST_Response|\WP_Error { if(!current_user_can('upload_files'))return new \WP_Error('forbidden','اجازه آپلود ندارید.',['status'=>403]);if(!Request::nonce_ok($r))return new \WP_Error('invalid_nonce','نشست فرم معتبر نیست.',['status'=>403]);$files=$_FILES['file']??null;if(!is_array($files)||empty($files['tmp_name']))return new \WP_Error('missing_file','فایلی ارسال نشده است.');$check=wp_check_filetype_and_ext((string)$files['tmp_name'],sanitize_file_name((string)$files['name']));$allowed=['image/jpeg','image/png','image/webp'];if(!in_array((string)($check['type']??''),$allowed,true))return new \WP_Error('invalid_type','نوع فایل مجاز نیست.');if((int)$files['size']>5*1024*1024)return new \WP_Error('file_too_large','حجم فایل بیشتر از 5MB است.');require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';$overrides=['test_form'=>false,'mimes'=>['jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp']];$upload=wp_handle_upload($files,$overrides);if(isset($upload['error']))return new \WP_Error('upload_failed',$upload['error']);$attachment=['post_mime_type'=>$upload['type'],'post_title'=>sanitize_text_field(pathinfo((string)$files['name'],PATHINFO_FILENAME)),'post_status'=>'inherit'];$aid=wp_insert_attachment($attachment,$upload['file']);if(is_wp_error($aid))return$aid;wp_update_attachment_metadata($aid,wp_generate_attachment_metadata($aid,$upload['file']));Queue::enqueue('generate_image_alt','attachment',(int)$aid,['attachment_id'=>(int)$aid],'alt:'.$aid,3,5);return rest_ensure_response(['id'=>(int)$aid,'url'=>wp_get_attachment_image_url((int)$aid,'large'),'mime'=>$upload['type']]); }
    public static function draft(\WP_REST_Request $r): \WP_REST_Response|\WP_Error { $uid=get_current_user_id(); if($r->get_method()==='POST' && !Request::nonce_ok($r))return new \WP_Error('invalid_nonce','نشست فرم معتبر نیست.',['status'=>403]);$key='_syvo_bd_draft';if($r->get_method()==='GET')return rest_ensure_response(['data'=>get_user_meta($uid,$key,true)]);$d=Request::json($r);update_user_meta($uid,$key,$d);return rest_ensure_response(['success'=>true]); }
}


final class Diagnostics {
    public static function all(): array { if(!function_exists('get_plugins'))require_once ABSPATH.'wp-admin/includes/plugin.php'; global $wpdb;$tables=DB::tables();$tableStatus=[];foreach($tables as $key=>$table)$tableStatus[$key]=(bool)$wpdb->get_var($wpdb->prepare('SHOW TABLES LIKE %s',$table));$plugins=get_plugins();return ['plugin_version'=>SYVO_BD_VERSION,'db_version'=>(string)get_option('syvo_bd_db_version',''),'wordpress'=>get_bloginfo('version'),'php'=>PHP_VERSION,'theme'=>wp_get_theme()->get('Name').' '.wp_get_theme()->get('Version'),'elementor'=>defined('ELEMENTOR_VERSION')?ELEMENTOR_VERSION:false,'rank_math'=>defined('RANK_MATH_VERSION')?RANK_MATH_VERSION:false,'woocommerce'=>defined('WC_VERSION')?WC_VERSION:false,'wordfence'=>isset($plugins['wordfence/wordfence.php']),'cron_test'=>'see Site Health / WP-Cron; scheduled queue '.(wp_next_scheduled('syvo_bd_process_queue')?'active':'missing'),'persistent_cache'=>(bool)wp_using_ext_object_cache(),'location_import_status'=>get_option('syvo_bd_location_import_status','unknown'),'ai'=>AIService::status(),'rest_namespace'=>SYVO_BD_REST_NAMESPACE,'tables'=>$tableStatus,'permalink'=>get_option('permalink_structure'),'locale'=>get_locale(),'timezone'=>wp_timezone_string()?:'UTC offset '.get_option('gmt_offset'),'memory_limit'=>ini_get('memory_limit')]; }
}
